version: '3.8'

services:
  basket.api:
    container_name: lde.basket.api
    build:
      context: .
      dockerfile: Basket/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - Redis__Host=www.urbanmonochrome.com:6380
    depends_on:
        - redis
    ports:   
        - 5003:5003
  redis:
    image: redis
    container_name: lde.redis
    ports:
        - 6380:6379
  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: Catalog/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - postgres
    ports:
      - 5000:5000    
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80
  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
  nginx:
    image: nginx
    container_name: lde.nginx
    ports:
      - 80:80
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1