version: '3.8'

services:
  basket.api:
    container_name: lde.basket.api
    build:
      context: .
      dockerfile: Basket/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - Authorization__Authority=http://www.urbanmonochrome.com:5002
      - Redis__Host=www.urbanmonochrome.com:6380
      - Redis__CacheTimeout=01:00:00
      - PathBase=http://www.urbanmonochrome.com:5003
    depends_on:
        - redis
    ports:   
        - 5003:5003
  redis:
    image: redis
    container_name: lde.redis
    ports:
        - 6380:6379
  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: Catalog/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
       - PathBase=http://www.urbanmonochrome.com:5000
       - Authorization__Authority=http://www.urbanmonochrome.com:5002
    depends_on:
      - postgres
    ports:
      - 5000:5000
  order.api:
    container_name: lde.order.api
    build:
      context: .
      dockerfile: Order/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5001
        - PathBase=http://www.urbanmonochrome.com:5001
        - CatalogApi=http://www.urbanmonochrome.com:5000
        - Authorization__Authority=http://www.urbanmonochrome.com:5002
    depends_on:
      - postgres
    ports:
      - 5001:5001
  notify.api:
    container_name: lde.notify.api
    build:
      context: .
      dockerfile: Notification/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5004
        - Authorization__Authority=http://www.urbanmonochrome.com:5002
        - PathBase=http://www.urbanmonochrome.com:5004
    ports:
      - 5004:5004
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80
  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
  nginx:
    image: nginx
    container_name: lde.nginx
    ports:
      - 80:80
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
  identityserver:
    container_name: lde.identityserver
    build:
      context: .
      dockerfile: Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002      
      - BasketApi=http://www.urbanmonochrome.com:5003
      - CatalogApi=http://www.urbanmonochrome.com:5000
      - OrderApi=http://www.urbanmonochrome.com:5001
      - NotificationApi=http://www.urbanmonochrome.com:5004
    ports:
      - 5002:5002
    depends_on:
      - postgres
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1